GROUP = {
    '1a': {
        "matematyka": [3, None],
        "wos": [1, None],
        "fizyka": [1, None],
        "j.polski": [4, None],
        "biologia": [3, None],
        "chemia": [3, None],
        "wf": [3, None],
        "religia": [2, None],
        "j.niemiecki": [2, None],
        "edb": [1, None],
        "geografia": [1, None],
        "j.łac": [1, None],
        "historia": [2, None],
        "informatyka": [1, None],
        "j.angielski": [3, None]
    },
    '1b': {
        "matematyka": [3, None],
        "wos": [1, None],
        "fizyka": [1, None],
        "j.polski": [7, None],
        "biologia": [1, None],
        "chemia": [1, None],
        "wf": [3, None],
        "religia": [2, None],
        "j.niemiecki": [2, None],
        "edb": [1, None],
        "geografia": [1, None],
        "j.łac": [1, None],
        "historia": [3, None],
        "informatyka": [1, None],
        "j.angielski": [3, None]
    },
    '1c': {
        "matematyka": [3, None],
        "wos": [1, None],
        "fizyka": [1, None],
        "j.polski": [4, None],
        "biologia": [3, None],
        "chemia": [3, None],
        "wf": [3, None],
        "religia": [2, None],
        "j.niemiecki": [2, None],
        "edb": [1, None],
        "geografia": [1, None],
        "j.łac": [1, None],
        "historia": [2, None],
        "informatyka": [1, None],
        "j.angielski": [3, None]
    },
    '1d': {
        "matematyka": [3, None],
        "wos": [2, None],
        "fizyka": [1, None],
        "j.polski": [6, None],
        "biologia": [1, None],
        "chemia": [1, None],
        "wf": [3, None],
        "religia": [2, None],
        "j.niemiecki": [2, None],
        "edb": [1, None],
        "geografia": [1, None],
        "j.łac": [1, None],
        "historia": [3, None],
        "informatyka": [1, None],
        "j.angielski": [3, None]
    },
    '1e': {
        "matematyka": [5, None],
        "wos": [1, None],
        "fizyka": [2, None],
        "j.polski": [4, None],
        "biologia": [1, None],
        "chemia": [1, None],
        "wf": [3, None],
        "religia": [2, None],
        "j.niemiecki": [2, None],
        "edb": [1, None],
        "geografia": [1, None],
        "j.łac": [1, None],
        "historia": [2, None],
        "informatyka": [2, None],
        "j.angielski": [3, None]
    },
    '1f': {
        "matematyka": [5, None],
        "wos": [1, None],
        "fizyka": [1, None],
        "j.polski": [4, None],
        "biologia": [1, None],
        "chemia": [1, None],
        "wf": [3, None],
        "religia": [2, None],
        "j.niemiecki": [2, None],
        "edb": [1, None],
        "geografia": [2, None],
        "j.łac": [1, None],
        "historia": [2, None],
        "informatyka": [2, None],
        "j.angielski": [3, None]
    },
    '1g': {
        "matematyka": [5, None],
        "wos": [1, None],
        "fizyka": [1, None],
        "j.polski": [4, None],
        "biologia": [1, None],
        "chemia": [1, None],
        "wf": [3, None],
        "religia": [2, None],
        "j.rosyjski": [2, None],
        "edb": [1, None],
        "geografia": [3, None],
        "j.łac": [1, None],
        "historia": [2, None],
        "informatyka": [1, None],
        "j.angielski": [3, None]
    },
    '2a': {
        "matematyka": [4, "BP"],
        "j.polski": [3, "AM"],
        "j.angielski": [3, "RO"],
        "j.niemiecki": [2, "MU"],
        "biologia": [4, "JW"],
        "chemia": [4, "Ma"],
        "informatyka": [1, None],
        "historia": [5, "PE"],
        "wos": [1, "BC"],
        "pp": [1, None],
        "geografia": [2, "Wg"],
        "religia": [2, None],
        "wf": [3, None],
        "fizyka": [1, "ŁS"]
    },
    '2b': {
        "matematyka": [4, "AT"],
        "j.polski": [6, "RS"],
        "j.angielski": [5, "EP"],
        "j.niemiecki": [2, "KJ"],
        "biologia": [2, "Sm"],
        "chemia": [2, "Ma"],
        "informatyka": [1, None],
        "historia": [3, "HW"],
        "wos": [1, "BC"],
        "pp": [1, None],
        "geografia": [2, "Wg"],
        "religia": [2, None],
        "wf": [3, None],
        "fizyka": [1, "ŁS"],
        "zaj.art": [1, None]
    },
    '2c': {
        "matematyka": [4, "MR"],
        "j.polski": [4, "PS"],
        "j.angielski": [3, "AB"],
        "j.niemiecki": [2, "MU"],
        "biologia": [4, "Wa"],
        "chemia": [5, "MC"],
        "informatyka": [1, None],
        "historia": [2, "VR"],
        "wos": [1, "BC"],
        "pp": [1, None],
        "geografia": [2, "CK"],
        "religia": [2, None],
        "wf": [3, None],
        "fizyka": [1, "ŁS"],
    },
    '2d': {
        "matematyka": [4, "AR"],
        "j.polski": [6, "MK"],
        "j.angielski": [3, "BH"],
        "j.niemiecki": [2, "GW"],
        "biologia": [2, "Sm"],
        "chemia": [2, "DW"],
        "informatyka": [1, None],
        "historia": [4, "PE"],
        "wos": [2, "VR"],
        "pp": [1, None],
        "geografia": [2, "Wg"],
        "religia": [2, None],
        "wf": [3, None],
        "fizyka": [1, "ŁS"],
    },
    '2e': {
        "matematyka": [6, "KT"],
        "j.polski": [4, "AM"],
        "j.angielski": [3, "RO"],
        "j.niemiecki": [3, "ER"],
        "biologia": [2, "Sm"],
        "chemia": [2, "DW"],
        "informatyka": [2, "DD"],
        "historia": [2, "VR"],
        "wos": [1, "BC"],
        "pp": [1, None],
        "geografia": [2, "ŁS"],
        "religia": [2, None],
        "wf": [3, None],
        "fizyka": [3, "ŁS"],
    },
    '2g': {
        "matematyka": [6, "AR"],
        "j.polski": [4, "PS"],
        "j.angielski": [4, "BH"],
        "j.rosyjski": [2, "ER"],
        "biologia": [2, "Sm"],
        "chemia": [2, "DW"],
        "informatyka": [1, "IW"],
        "historia": [2, "PE"],
        "wos": [1, "BC"],
        "pp": [1, None],
        "geografia": [3, "ŁS"],
        "religia": [2, None],
        "wf": [3, None],
        "fizyka": [1, "ŁS"],
    },
    '3a': {
        "matematyka": [3, "KT"],
        "chemia": [5, "Ma"],
        "biologia": [6, "JW"],
        "j.polski": [4, "MJ"],
        "j.angielski": [3, "KJ"],
        "wf": [3, None],
        "historia": [2, "HV"],
        "j.niemiecki": [2, "MW"],
        "religia": [1, None],
    },
    '3b': {
        "matematyka": [3, "KT"],
        "j.polski": [4, "MJ"],
        "j.angielski": [3, "EP"],
        "j.hiszpański": [1, "RO"],
        "wf": [3, None],
        "historia": [5, "PE"],
        "religia": [1, None],
        "wos": [3, "BC"],
        "geografia": [5, "CK"],
    },
    '3c': {
        "matematyka": [3, "AR"],
        "j.polski": [4, "MJ"],
        "j.angielski": [3, "BH"],
        "j.niemiecki": [2, "MW"],
        "wf": [3, None],
        "historia": [2, "VR"],
        "religia": [1, None],
        "chemia": [5, "MC"],
        "biologia": [6, "Wa"],
    },
    '3d': {
        "matematyka": [3, "KT"],
        "j.polski": [8, "AM"],
        "j.angielski": [3, "AB"],
        "j.niemiecki": [2, "KJ"],
        "wf": [3, None],
        "historia": [5, "VR"],
        "religia": [1, None],
        "wos": [2, "AS"],
        "przyroda": [2, "Sm"],
    },
    '3e': {
        "matematyka": [7, "MV"],
        "j.polski": [4, "PS"],
        "j.angielski": [4, "JK"],
        "j.niemiecki": [4, "GW"],
        "wf": [3, None],
        "historia": [2, "HV"],
        "religia": [1, None],
        "fizyka": [4, "MB"],
    },
    '3f': {
        "matematyka": [7, "AT"],
        "j.polski": [4, "MJ"],
        "j.angielski": [6, "EZ"],
        "j.rosyjski": [2, "ER"],
        "wf": [3, None],
        "historia": [2, "VR"],
        "religia": [1, None],
        "geografia": [4, "CK"],
    },
}