# Generated by Django 3.1.7 on 2021-03-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('login', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
