# Generated by Django 3.1.7 on 2021-03-28 18:57
# pylint: disable=C0114, C0115, C0103
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='dsada', max_length=255),
            preserve_default=False,
        ),
    ]
