# Generated by Django 3.1.7 on 2021-12-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_auto_20210328_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_name', models.CharField(blank=True, max_length=50, null=True)),
                ('pref_subject', models.JSONField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Classrooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('lesson_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lesson_name', models.CharField(blank=True, max_length=50, null=True)),
                ('classroom', models.CharField(blank=True, max_length=50, null=True)),
                ('lesson_pref', models.JSONField(blank=True, null=True)),
                ('numbers_of_lesson', models.IntegerField(blank=True, null=True)),
                ('class_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Lessons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planners',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Planners',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('pool_id', models.IntegerField(primary_key=True, serialize=False)),
                ('teacher_pref', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Polls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacher_email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Teachers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timetables',
            fields=[
                ('timetable_id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Timetables',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
