# Generated by Django 3.1.7 on 2021-12-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_auto_20211208_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='classrooms',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lessons',
            options={},
        ),
        migrations.AlterModelOptions(
            name='planners',
            options={},
        ),
        migrations.AlterModelOptions(
            name='polls',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='timetables',
            options={},
        ),
    ]
